name: tools
description: Development tools for score_system.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.9.2

resolution: workspace

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
